# _config.yml
title: "Luke Maddock"
email: "luke.maddock@colostate.edu"
description: "Economics PhD Candidate @ CSU"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Luke Maddock"
  avatar: "/assets/img/avatar.jpg"
  bio: "Economics PhD Candidate, Colorado State University"
  location: "Fort Collins, Colorado"

social:
  email: luke.maddock@colostate.edu
  twitter: lukemaddock
  github: l-maddock
  scholar: https://scholar.google.com/citations?user=L5dqWugAAAAJ&hl=en
  orcid: 0000-0001-5701-3425
